version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Debug
  - Release

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user
  - conan --version

before_build:
  - md build
  - cd build
  - conan install .. -s build_type=$(configuration)
  - cmake .. -G "Visual Studio 15 2017 Win64"

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\DbSQLiteAdapter.sln

artifacts:
  - path: 'build\lib\DbSQLiteAdapter.lib'
    name: DbSQLiteAdapter.lib
